dist: trusty

language: c

cache:
    - ccache
    - pip

compiler:
    - gcc

before_install:
    - sudo add-apt-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes --force-yes valac libglib2.0-bin
      libglib2.0-dev libmemcached-dev python3-pip
    - sudo pip3 install meson
    - wget https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-linux.zip
    - sudo unzip ninja-linux.zip -d /usr/local/bin

before_script:
    - mkdir build
    - meson.py . build
    - ninja -C build -v

script:
    - ninja -C build -v test
